#!/bin/sh
# /etc/init.d/sebcamctrl
### BEGIN INIT INFO
# Provides:        sebcamctrl
# Required-Start:  $local_fs $network $remote_fs $syslog $time
# Required-Stop:   $local_fs $network $remote_fs $syslog $time
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Controls sebcam.py app. exec.
# Description:       Controls sebcam.py application execution (CSA STRATOS)
### END INIT INFO
PATHAPP="/home/seb/sebcam.py &"
PIDAPP="/home/seb/sebcam_pid.txt"
case $1 in
        start)
                echo "starting"
                $PATHAPP
        ;;
        stop)
                echo "stopping"
                PID=$(cat $PIDAPP)
                kill $PID
        ;;
esac

